version: "3.6"

networks:
  default:
    driver: bridge

services:
    # This container has to be exclude from production configurations.
    # its main purpose is to allow you to access containers running in the host machine
    # from inside of docker.
    docker-host:
        image: qoomon/docker-host
        cap_add: ["NET_ADMIN", "NET_RAW"]
        # mem_limit: 8M
        restart: on-failure
        networks:
            - default

    rabbitmq:
        restart: always
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - 15672
        networks:
            - default
        volumes:
            - ./local/rabbitmq:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/

    django:
        restart: on-failure
        image: django-powerdispatcher
        env_file:
            - .env
        build:
            context: ./
        networks:
            - default
        ports:
            - ${DJANGO_PORT}:8000
        volumes:
            - ./:/code
        command: >
            bash -c ' pipenv install --system --skip-lock --dev && python manage.py runserver 0.0.0.0:8000'
        environment:
            - DJANGO_SETTINGS_MODULE=service.settings

    celery-worker:
        restart: on-failure
        image: django-powerdispatcher
        env_file:
            - .env
        build:
            context: ./
        volumes:
            - ./:/code
        command: >
            bash -c ' pipenv install --system --skip-lock --dev && sleep 14 && watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A service worker --concurrency 4 -O fair -Q main_queue --beat --scheduler django -l INFO'
        depends_on:
            - rabbitmq
        networks:
            - default

    # celery-worker-test:
    #     restart: on-failure
    #     image: django-powerdispatcher
    #     env_file:
    #         - .env
    #     build:
    #         context: ./
    #     volumes:
    #         - ./:/code
    #     command: >
    #         bash -c '
    #         pipenv install --system --skip-lock --dev &&
    #         sleep 14 &&
    #         watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A service worker --concurrency 2 -O fair -Q main_queue -l INFO'
    #     depends_on:
    #         - rabbitmq

    chrome:
        restart: always
        image: selenium/node-chrome:4.5.0-20221017
        shm_size: 2gb
        depends_on:
            - selenium-hub
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=${NUMBER_OF_WEBDRIVER_PER_NODE}
            - NODE_MAX_SESSION=${NUMBER_OF_WEBDRIVER_PER_NODE}
            - START_XVFB=true
            - VNC_NO_PASSWORD=1
            - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps= -Dselenium.LOGGER.level=WARNING
            - CONTAINER_HOST_IP
            - SCREEN_WIDTH=1366
            - SCREEN_HEIGHT=768
        ports:
            - "${WEBDRIVER_PORT_START}-${WEBDRIVER_PORT_END}:5900"
        stdin_open: true
        tty: true
        networks:
            - default

    selenium-hub:
        restart: always
        image: selenium/hub:4.5.0-20221017sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

        environment:
            - GRID_TIMEOUT=${GRID_TIMEOUT}
            - GRID_BROWSER_TIMEOUT=${GRID_TIMEOUT}
            - GRID_MAX_SESSION=${GRID_MAX_SESSION}
            - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
        stdin_open: true
        tty: true
        networks:
            - default

    db:
        image: postgres:16.2
        env_file:
            - .env.dev
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/prolocksmiths/
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL:${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD:${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin-data:/var/lib/pgadmin
    
volumes:
    postgres:
    pgadmin-data:
