REM Set additional environment variables
set USER_ID=%USERNAME%
set GROUP_ID=%USERDOMAIN%
set CONTAINER_HOST_IP=docker-host

REM DEFAULT WEBHUB AND NODES CONFIGURATIONS
set NUMBER_OF_WEBDRIVER_NODES=%NUMBER_OF_WEBDRIVER_NODES:0%
set NUMBER_OF_WEBDRIVER_PER_NODE=1
set WEBDRIVER_PORT_START=5901
set /a WEBDRIVER_PORT_END=WEBDRIVER_PORT_START + NUMBER_OF_WEBDRIVER_NODES - 1
if %WEBDRIVER_PORT_END% lss %WEBDRIVER_PORT_START% set /a WEBDRIVER_PORT_END+=1
set /a GRID_TIMEOUT=300
set /a GRID_MAX_SESSION=NUMBER_OF_WEBDRIVER_NODES * NUMBER_OF_WEBDRIVER_PER_NODE * 5
