# Generated by Django 4.1.2 on 2022-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
