# Generated by Django 3.2.16 on 2022-10-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
