# Generated by Django 4.1.2 on 2022-11-01 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraperlog',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Scraper Logs'},
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='first_scraping_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='All scraped records will start from this date'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='powerdispatch_account',
            field=models.CharField(default='Account placeholder', max_length=100, verbose_name='Account id used to connect to powerdispatch app'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='powerdispatch_password',
            field=models.CharField(default='Account placeholder', max_length=100, verbose_name='Account password used to connect to powerdispatch app'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='powerdispatch_username',
            field=models.CharField(default='Username placeholder', max_length=100, verbose_name='Account username used to connect to powerdispatch app'),
        ),
    ]
