# Generated by Django 5.0.4 on 2024-08-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0002_projectconfiguration_first_date_to_review_follow_up_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='follow_up_given_by_alternative_technician',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
