# Generated by Django 4.1.2 on 2022-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0002_alter_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
