# Generated by Django 5.0.4 on 2024-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0005_ticket_follow_up_reviewed_failed_last_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='follow_up_reviewed_failed_last_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
