# Generated by Django 4.1.2 on 2022-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0005_alter_branch_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
