# Generated by Django 5.0.4 on 2024-10-10 21:12

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0006_alter_ticket_follow_up_reviewed_failed_last_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('first_time_caller', models.BooleanField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('medium', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign', models.CharField(blank=True, max_length=500, null=True)),
                ('ad_group', models.CharField(blank=True, max_length=500, null=True)),
                ('call_status', models.CharField(blank=True, max_length=500, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('number_name', models.CharField(blank=True, max_length=500, null=True)),
                ('google_ads_gclid', models.CharField(blank=True, max_length=500, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=500, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_talk_time_percent', models.IntegerField(blank=True, null=True)),
                ('agent_talk_time_percent', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('call_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
