# Generated by Django 4.1.2 on 2022-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdispatcher', '0007_alter_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='open_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='technician_availability',
            field=models.IntegerField(default=0),
        ),
    ]
